apiVersion: v1
kind: Service
metadata:
   name: wil-playground
   namespace: dev
spec:
   type: NodePort
   selector:
      app: wil-playground
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001
