apiVersion: v1
kind: Service
metadata:
   name: wil-playground
   namespace: dev
spec:
   type: "loadBalancer"
   selector:
      app: wil-playground
   ports:
      - protocol: TCP
        port: 3000
        targetPort: 8888
